baseURL = "https://nightingalehq.ai"
languageCode = "en-us"
title = "Nightingale HQ"
theme = "hugo-serif-theme"

[params]
#google_analytics_id=""
cta_title = "We're launching soon! Be the first to hear."
cta_url = "http://eepurl.com/ga2dmj"
cta_button = "Sign up"

[params.social]
twitter = "//twitter.com/nightingalehqai"
medium = "//medium.com/nightingale-hq"
linkedin = "//www.linkedin.com/company/nightingale-hq"

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 0

[[menu.main]]
	name = "The benefits of Data Science"
	url = "/benefits/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/team/"
    weight = 2

[[menu.main]]
    name = "Sign up"
    url = "http://eepurl.com/ga2dmj"
    weight = 4
