baseURL = "https://nightingalehq.ai/"
languageCode = "en-us"
title = "Nightingale HQ"
theme = "hugo-serif-theme"

[params]
#google_analytics_id=""
cta_title = "We're launching soon! Be the first to hear."
cta_url = "register"
cta_button = "Sign up"

[params.social]
twitter = "//twitter.com/nightingalehqai"
medium = "//medium.com/nightingale-hq"
linkedin = "//www.linkedin.com/company/nightingale-hq"

[params.twitter]
card = "player"
title = "Nightingale HQ"
site = "@nightingalehqai"
description = "Helping businesses build and implement a data strategy"
video = "container.html"
player_width = 1920
player_height = 1080
image = "images/doggothumbnail.jpg"
image_alt = "Playful dog getting ready"

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1

[[menu.main]]
	name = "The benefits of Data Science"
	url = "benefits"
    weight = 2

[[menu.main]]
    name = "About"
    url = "team"
    weight = 3

[[menu.main]]
    name = "Sign up"
    url = "register"
    weight = 4
